server:
  port: 8989
  
spring:
  application:
    name: turbine

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/   
       
  server:
    waitTimeInMsWhenSyncEmpty: 0
  instance:
    hostname: localhost
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 5
    metadataMap:
      cluster: WEBSHOP

turbine:
  aggregator:
    clusterConfig: WEBSHOP
  appConfig: user-service,product-service,api-gateway,category-service,uaa-service,search-service
  clusterNameExpression: metadata['cluster']