server:
  port: 8989
  
spring:
  application:
    name: turbine

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/   
       
  server:
    waitTimeInMsWhenSyncEmpty: 0
  instance:
    hostname: localhost
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 5
    
turbine:
  aggregator:
    clusterConfig: WEBSHOP
  appConfig: USER-SERVICE, CATEGORY-SERVICE, PRODUCT-SERVICE
  ConfigPropertyBasedDiscovery:
    WEBSHOP:
      instances:  USER-SERVICE
    default:
      instances:  USER-SERVICE
      
 #turbine.ConfigPropertyBasedDiscovery.WEBSHOP.instances