version: '3.3'

services:
    database:
        image: mavogel/hska-vis-web-shop-db-image
        environment:
            MYSQL_ROOT_PASSWORD: c8de110f37300a53a971749
            MYSQL_DATABASE: webshop
            MYSQL_USER: webshopuser
            MYSQL_PASSWORD: 240b2c6d58ff2ce2f508b49f
        ports:
            - "3306:3306"

    eureka:
        build: Eureka-Server/.
        ports:
            - "8761:8761"

    turbine:
        build: Turbine/.
        ports:
            - "8989:8989"
        links:
            - "eureka:eureka"
            - "user:user"
            - "category:category"
            - "search:search"
            - "zuul:zuul"

    user:
        build: Core/User-Core/.
        ports:
            - "8083:8080"
        depends_on:
            - "eureka"
        links:
            - "database:database"
            - "eureka:eureka"

    category:
        build: Core/Category-Core/.
        ports:
            - "8081:8080"
        depends_on:
            - "eureka"
        links:
            - "database:database"
            - "eureka:eureka"

    product:
        build: Core/Product-Core/.
        ports:
            - "8082:8080"
        depends_on:
            - "eureka"
        links:
            - "database:database"
            - "eureka:eureka"

    search:
        build: Composite/Search-Service/.
        ports:
            - "8084:8080"
        depends_on:
            - "eureka"
        links:
            - "eureka:eureka"
            - "user:user"

    zuul:
        build: Zuul-Server/.
        ports:
            - "8080:8081"
        depends_on:
            - "eureka"
            - "user"
            - "search"
            - "category"
        links:
            - "eureka:eureka"
            - "user:user"
            - "search:search"
            - "category:category"

    front-end:
        build: FrontEnd/.
        ports:
          - "8787:8080"