server:
  port: 8081


info:
  component: Edge Server

zuul:
  routes:
    user-service:
      path: /users/**
#      serviceId: user-service
      url: http://user:8080
      strip-prefix: false

    category-service:
      path: /category/**
      url: http://category:8080
      strip-prefix: false

    search-service:
      path: /search/**
      url: http://search:8080
      strip-prefix: false

    product-service:
      path: /product/**
      url: http://product:8080
      strip-prefix: false


eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
    registerWithEureka: false


ribbon:
  eureka:
    enabled: true
