server:
  port: 8081


info:
  component: Edge Server

zuul:
  routes:
    user-service:
      path: /users/**
      serviceId: USER-SERVICE
      strip-prefix: false

    category-service:
      path: /category/**
      serviceId: CATEGORY-SERVICE
      strip-prefix: false

    search-service:
      path: /search/**
      serviceId: SEARCH-SERVICE
      strip-prefix: false

    product-service:
      path: /product/**
      serviceId: PRODUCT-SERVICE
      strip-prefix: false

    oauth-service:
      path: /auth/**
      url: http://auth:8080

eureka:
  instance:
    preferIpAdress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/

endpoints:
  routes:
    sensitive: false

ribbon:
  readTimeout: 30000
  eureka:
    enabled: true

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 30000

security:
  basic:
    enabled: false
  oauth2:
    sso:
      login-path: /login
    client:
      access-token-uri: http://auth:8080/oauth/token
      user-authorization-uri: /auth/oauth/authorize
      client-id: client
      client-secret: secret
    resource:
      jwt:
        keyValue: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnGp/Q5lh0P8nPL21oMMrt2RrkT9AW5jgYwLfSUnJVc9G6uR3cXRRDCjHqWU5WYwivcF180A6CWp/ireQFFBNowgc5XaA0kPpzEtgsA5YsNX7iSnUibB004iBTfU9hZ2Rbsc8cWqynT0RyN4TP1RYVSeVKvMQk4GT1r7JCEC+TNu1ELmbNwMQyzKjsfBXyIOCFU/E94ktvsTZUHF4Oq44DBylCDsS1k7/sfZC2G5EU7Oz0mhG8+Uz6MSEQHtoIi6mc8u64Rwi3Z3tscuWG2ShtsUFuNSAFNkY7LkLn+/hxLCu2bNISMaESa8dG22CIMuIeRLVcAmEWEWH5EEforTg+QIDAQAB
          -----END PUBLIC KEY-----
      id: openid
      serviceId: ${PREFIX:}resource
