server:
  port: 8081

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: /info
    healthCheckUrlPath: /health

zuul:
  ignored-services: '*'
  routes:
    user-proxy: /user-api/**