server:
  port: 8080

spring:
  application:
    name: search-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 5
    status-page-url-path: /info
    health-check-url-path: /health
    metadataMap:
      instanceId: "${spring.application.name}:${random.value}"
